name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: DockerHub Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Pull latest image
        run: docker pull smw0807/smw-chatbot:1.0.0

      - name: Stop and remove old container
        run: |
          docker stop smw-chatbot || true
          docker rm smw-chatbot || true

      - name: Run new container
        env:
          APP_PORT: ${{ secrets.APP_PORT }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_API_URL: ${{ secrets.ANTHROPIC_API_URL }}
          ANTHROPIC_MODEL: ${{ secrets.ANTHROPIC_MODEL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        run: |
          docker run -d \
            --name smw-chatbot \
            --restart always \
            -e APP_PORT="$APP_PORT" \
            -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
            -e ANTHROPIC_API_URL="$ANTHROPIC_API_URL" \
            -e ANTHROPIC_MODEL="$ANTHROPIC_MODEL" \
            -e FRONTEND_URL="$FRONTEND_URL" \
            -p $APP_PORT:$APP_PORT \
            smw0807/smw-chatbot:1.0.0
